### ISSUE TITLE
every post can be a translation or a correction

### ISSUE THREAD

**Issue by ghost** [tent/tent.io#151]
just to make it clear:

```
post:
  type: essay

  mentions:
    entity: <your friends entity>
    id: <some status with complains about how old-world grammar is old>

  translation:
    source_lang: en-GB
    target_lang: en-US
    source:
      type: tent-post (can be an url)
      entity: <some random entity>
      id: <some long essay with UK-spelled words like 'colour', 'favourite'>
```

```
post:
  type: photo

  mentions:
    entity: <entity>
    id: <some status with some false info>

  correction:
    note: <note about how that false fact is not true>
```

```
post:
  type: essay

  mentions:
    entity: <entity>
    id: <some essay with grammar errors>

  correction:
    correct: <full essay with corrected text> (diff will be showed by an app)
    note: <a note about corrections in your grammar, plus some links to rules used>
```
